### ISSUE TITLE
我一用就报错。这是为虾米。报错title:Body is not defined。

### ISSUE THREAD

**Issue by wuxiaolan91** [Houfeng/faked#1]
我一用就报错了：
我的源代码
```
this.$http.get('/api/getBugList', {
        ID: 12345
    })
        .then(function (response) {
            console.log(response);
        })
        .catch(function (error) {
            console.log(error);
        });
```
Uncaught ReferenceError: Body is not defined
    at METHODS.forEach.method (eval at <anonymous> (http://localhost:8080/app.js:857:1), <anonymous>:38:3)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:857:1), <anonymous>:37:9)
    at Object.<anonymous> (http://localhost:8080/app.js:857:1)
    at __webpack_require__ (http://localhost:8080/app.js:660:30)
    at fn (http://localhost:8080/app.js:84:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:863:1), <anonymous>:2:14)
    at Object.<anonymous> (http://localhost:8080/app.js:863:1)
    at __webpack_require__ (http://localhost:8080/app.js:660:30)
    at fn (http://localhost:8080/app.js:84:20)

**Comment by Houfeng** [comment]
`this.body` 是小写的

**Comment by wuxiaolan91** [comment]
我没有写 this.body 或者 this.Body 这样的代码。 这个报错是通过我的引用， 然后源码里报错的。

**Comment by Houfeng** [comment]
很感谢您的反馈，能否提供一个能重现的示例？
